
-- Exercício (2) Seleciona nome, sobrenome cargo, salário

-- dos empregados que possuem salário maior que 7000,

-- e ordena do menor para o maior.

SET SERVEROUTPUT ON
--
DECLARE
CURSOR CURSOR_EMPREGADOS IS
SELECT FIRST_NAME,LAST_NAME,JOB_ID,SALARY
FROM EMPLOYEES WHERE SALARY >= 7000 ORDER BY SALARY ASC ;
V_EMPREGADO CURSOR_EMPREGADOS%ROWTYPE;
--
BEGIN
OPEN CURSOR_EMPREGADOS;
LOOP
FETCH CURSOR_EMPREGADOS INTO V_EMPREGADO;
IF CURSOR_EMPREGADOS%FOUND THEN
--
DBMS_OUTPUT.PUT('NOME: '||V_EMPREGADO.FIRST_NAME);
DBMS_OUTPUT.PUT('SOBRENOME:'||V_EMPREGADO.LAST_NAME);
DBMS_OUTPUT.PUT('CARGO: '||V_EMPREGADO.JOB_ID);
DBMS_OUTPUT.PUT('SALARIO: '||V_EMPREGADO.SALARY);
--
ELSE
    --
    EXIT;
    END IF;
    END LOOP;
    --
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(SQLERRM);
--
END;
