

-- Exercícios utilizando o SCHEMA HR do banco Oracle.

-- Exercicio 1

SET SERVEROUTPUT ON
--
DECLARE
-- Declara um cursor
CURSOR CRS_1 IS
SELECT FIRST_NAME, JOB_ID, DEPARTMENT_NAME
FROM EMPLOYEES, DEPARTMENTS,LOCATIONS WHERE
EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
AND DEPARTMENTS.DEPARTMENT_ID = 90
AND LOCATIONS.CITY = 'Sao Paulo'
AND EMPLOYEES.MANAGER_ID = 100;
--
-- Cria uma variável para armazenar os dados do cursor
VRL_1 CRS_1%ROWTYPE;
BEGIN
OPEN CRS_1;
LOOP
FETCH CRS_1 INTO VRL_1;
--
-- Exibe os dados caso existam no cursor
IF CRS_1%FOUND THEN
DBMS_OUTPUT.PUT_LINE('NOME: '||VRL_1.FIRST_NAME
||' CARGO: '||VRL_1.JOB_ID
||' DEPARTAMENTO: '||VRL_1.DEPARTMENT_NAME);
ELSE
--
EXIT;
END IF;
END LOOP;
--
CLOSE CRS_1;
--
-- Trata os possíveis erros
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERRO: '||SQLERRM);
END;


-- Exercício (2) Seleciona nome, sobrenome cargo, salário

-- dos empregados que possuem salário maior que 7000,

-- e ordena do menor para o maior.

SET SERVEROUTPUT ON
--
DECLARE
CURSOR CURSOR_EMPREGADOS IS
SELECT FIRST_NAME,LAST_NAME,JOB_ID,SALARY
FROM EMPLOYEES WHERE SALARY >= 7000 ORDER BY SALARY ASC ;
V_EMPREGADO CURSOR_EMPREGADOS%ROWTYPE;
--
BEGIN
OPEN CURSOR_EMPREGADOS;
LOOP
FETCH CURSOR_EMPREGADOS INTO V_EMPREGADO;
IF CURSOR_EMPREGADOS%FOUND THEN
--
DBMS_OUTPUT.PUT('NOME: '||V_EMPREGADO.FIRST_NAME);
DBMS_OUTPUT.PUT('SOBRENOME:'||V_EMPREGADO.LAST_NAME);
DBMS_OUTPUT.PUT('CARGO: '||V_EMPREGADO.JOB_ID);
DBMS_OUTPUT.PUT('SALARIO: '||V_EMPREGADO.SALARY);
DBMS_OUTPUT.PUT_LINE('====================||'); 
--
ELSE
    --
    EXIT;
    END IF;
    END LOOP;
    --
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(SQLERRM);
--
END;
