

--LABELS (RÓTULOS).

--Exemplo de utillização de um Label.
SET SERVEROUTPUT ON
DECLARE
BEGIN
<<LOOP_EXTERNO>>
FOR VAR_EXTERNA IN 1..30 LOOP
DBMS_OUTPUT.PUT_LINE('Contador externo:'||VAR_EXTERNA);
<<LOOP_INTERNO>>
FOR VAR_INTERNA IN 1..20 LOOP
DBMS_OUTPUT.PUT_LINE('Contador interno'||VAR_INTERNA);
IF VAR_EXTERNA = 10 THEN
EXIT LOOP_EXTERNO;
END IF;
END LOOP INTERNO;
END LOOP EXTERNO;
END;



--INSTRUÇÃO GOTO.

-- Exemplo de utilização da instrução GOTO.
SET SERVEROUTPUT ON
DECLARE
BEGIN
FOR VRL_CONTADOR IN 1..50 LOOP
DBMS_OUTPUT.PUT_LINE('Contador'||VRL_CONTADOR);
IF VRL_CONTADOR = 20 THEN
GOTO FIM;
END IF;
END LOOP;
<<FIM>>
DBMS_OUTPUT.PUT_LINE('Programa finalizado');
END;
/
