--    Programação para Banco de Dados -
--              02-06-2020
-- ------------- TRIGGERS -------------

-- CRIANDO AS TABELAS PARA TESTES
CREATE TABLE PRODUTO(
    codigo NUMBER(4) PRIMARY KEY,
    valor  NUMBER(7,2)NOT NULL
    );

INSERT INTO PRODUTO VALUES(1001,235.00);
INSERT INTO PRODUTO VALUES(1002,345.00);
INSERT INTO PRODUTO VALUES(1003,445.00);
INSERT INTO PRODUTO VALUES(1004,445.00);
COMMIT;

CREATE TABLE VALOR_PRODUTO (
    CODIGO NUMBER(4),
    VALOR_ANTERIOR NUMBER(7,2)NOT NULL,
    VALOR_NOVO NUMBER(7,2)NOT NULL
    );
COMMIT;

 -- CRIANDO UM TRIGGER
   CREATE OR REPLACE TRIGGER TRIG_VERIFICA_VALOR_PROD
 -- AFTER DEPOIS DE ATUALIZAR A TABLE PRODUTO
 -- ELE PEGA OS VALORES E DISPARA O EVENTO
    AFTER UPDATE ON PRODUTO
 -- PARA CADA LINHA ATUALIZADA
    FOR EACH ROW
        BEGIN
        INSERT INTO VALOR_PRODUTO
            (CODIGO,VALOR_ANTERIOR,VALOR_NOVO,DATA_ATUALIZACAO)
        VALUES
            (:OLD.CODIGO,:OLD.VALOR,:NEW.VALOR,SYSDATE);
        END;


-- INCLUINDO O CAMPO DATA NA TABELA VALOR_PRODUTO
ALTER TABLE VALOR_PRODUTO ADD DATA_ATUALIZACAO DATE;

-- VERIFICANDO AS ALTERAÇÕES NA TABELA VALOR_PRODUTO
UPDATE PRODUTO SET VALOR = 15.90 WHERE CODIGO = 1001;
UPDATE PRODUTO SET VALOR = 25.90 WHERE CODIGO = 1002;
UPDATE PRODUTO SET VALOR = 35.90 WHERE CODIGO = 1003;
UPDATE PRODUTO SET VALOR = 45.90 WHERE CODIGO = 1004;
COMMIT;

SELECT * FROM PRODUTO;

SELECT * FROM VALOR_PRODUTO;

-- CRIANDO UM TRIGGER PARA VERIFICAR O HORÁRIO
CREATE OR REPLACE TRIGGER TRIG_SEG_PROD
-- ANTES DE INSERIR NA TABELA PRODUTO
    BEFORE INSERT -- OR UPDATE OR REPLACE
    ON PRODUTO
-- INICIO
BEGIN
    --SYSDATE FUNCAO DE HORA
    --HH24 -- 0 ATÉ 24 HORAS
    --MI MINUTOS
    IF(TO_CHAR(SYSDATE,'HH24:MI')
    --SE NÃO ESTIVER ENTRE O HORÁRIO ABAIXO, MOOSTRA O ERRO
    NOT BETWEEN '09:00' AND '16:00')THEN
    Raise_Application_Error(-20500,'HORÁRIO NÃO PERMITIDO PARA ESSA OPERAÇÃO');
    END IF;
    END;

    INSERT INTO PRODUTO VALUES(1005,234.90);
